create table "public"."favorite_offers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "offer_id" bigint,
    "user_id" text default requesting_user_id()
);


alter table "public"."favorite_offers" enable row level security;

CREATE UNIQUE INDEX favorite_offers_pkey ON public.favorite_offers USING btree (id);

alter table "public"."favorite_offers" add constraint "favorite_offers_pkey" PRIMARY KEY using index "favorite_offers_pkey";

alter table "public"."favorite_offers" add constraint "public_favorite_offers_offer_id_fkey" FOREIGN KEY (offer_id) REFERENCES offers(id) ON DELETE CASCADE not valid;

alter table "public"."favorite_offers" validate constraint "public_favorite_offers_offer_id_fkey";

grant delete on table "public"."favorite_offers" to "anon";

grant insert on table "public"."favorite_offers" to "anon";

grant references on table "public"."favorite_offers" to "anon";

grant select on table "public"."favorite_offers" to "anon";

grant trigger on table "public"."favorite_offers" to "anon";

grant truncate on table "public"."favorite_offers" to "anon";

grant update on table "public"."favorite_offers" to "anon";

grant delete on table "public"."favorite_offers" to "authenticated";

grant insert on table "public"."favorite_offers" to "authenticated";

grant references on table "public"."favorite_offers" to "authenticated";

grant select on table "public"."favorite_offers" to "authenticated";

grant trigger on table "public"."favorite_offers" to "authenticated";

grant truncate on table "public"."favorite_offers" to "authenticated";

grant update on table "public"."favorite_offers" to "authenticated";

grant delete on table "public"."favorite_offers" to "service_role";

grant insert on table "public"."favorite_offers" to "service_role";

grant references on table "public"."favorite_offers" to "service_role";

grant select on table "public"."favorite_offers" to "service_role";

grant trigger on table "public"."favorite_offers" to "service_role";

grant truncate on table "public"."favorite_offers" to "service_role";

grant update on table "public"."favorite_offers" to "service_role";


